name: OrynPlugins
description: '${description}'
version: '${version}'

main: net.oryn.mc.orynPlugins.OrynPlugins
paperPluginLoader: net.oryn.mc.orynPlugins.OrynPluginsLoader
api-version: '1.21.1'
load: STARTUP

authors: [ Fahry-a ]

commands:
  oryn:
    description: OrynPlugins main command
    usage: /oryn <module|help>
    permission: oryn.admin

permissions:
  oryn.admin:
    description: Allows use of OrynPlugins commands
    default: op
