name: Build & Publish to Maven Repo

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build & Publish to Maven Repo
        run: ./gradlew clean build publish --no-daemon
        env:
          ORG_GRADLE_PROJECT_orynRepoUsername: ${{ secrets.ORYN_USERNAME }}
          ORG_GRADLE_PROJECT_orynRepoPassword: ${{ secrets.ORYN_PASSWORD }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OrynPlugins-${{ github.ref_name }}
          path: build/libs/*.jar
